Endringer jeg mener er grei for alle oss i teamet å ha som standarder
navikt/aap-soknad-api pull request #430
Opened 2022-09-19 08:30 UTC by sturleh

Det ligger 2 ting i denne pr som jeg kunne tenkt at vi diskuterte om vi ønsker å gjøre:
1. I byggene våre, mener jeg at vi kan unngå å deploye dersom vi eks bare gjør en endring i en README.MD. 
2. Jeg har lagt til standard READMEmd for åpne repoer i NAV.

Vedrørende punkt 1, så er det greit å ikke bygge nytt fordi en har en tekstendring. Jeg emner vi bør unngå å deploye apper bare fordi vi skriver litt i en readme fil, uansett hvor den er i prosjektet.

Vedrørende punkt 2, så er det jo en del standard filer vi skal benytte se [offentlige retninslinjer](https://github.com/navikt/offentlig). lisens, readme og kontaktinfo

2022-09-19 19:13 UTC, jan-olaveide requested changes

2022-09-19 19:13 UTC, jan-olaveide commented on README.md
> +Den benytter seg av [AAP-FSS-Proxy](https://github.com/navikt/aap-fss-proxy) for interne registertjenester, felles forretningslogikk for disse to repoene er samlet i  [AAP-Domain](https://github.com/
Ikke bruk av fss-proxy nå lenger

2022-09-19 19:13 UTC, jan-olaveide commented on README.md
> +Den benytter seg av [AAP-FSS-Proxy](https://github.com/navikt/aap-fss-proxy) for interne registertjenester, felles forretningslogikk for disse to repoene er samlet i  [AAP-Domain](https://github.com/
Ikke logikk, egentlig. Kun DTOer og noen enkle verdiobjekter, men der er det kraftig ryddet nå.

2022-09-19 19:13 UTC, jan-olaveide commented on README.md
> +- metadata knyttet til søknader, eksterne oppgaver og beskjerder på mine aap.
samt kvitteringer på eksterne notifikasjoner

2022-09-19 19:13 UTC, jan-olaveide commented on README.md
> +- å bygge lokalt, krever enten koblig mot GCP-dev db eller å [kommentere ut testene i](src/test/kotlin/no/nav/aap/api/søknad/SøknadDBTest.kt)
Krever docker/colima lokalt

2022-09-21 07:17 UTC, sturleh commented on README.md
> +Den benytter seg av [AAP-FSS-Proxy](https://github.com/navikt/aap-fss-proxy) for interne registertjenester, felles forretningslogikk for disse to repoene er samlet i  [AAP-Domain](https://github.com/
Hvordan bør dette formuleres da?

2022-09-21 07:18 UTC, sturleh commented on README.md
> +- metadata knyttet til søknader, eksterne oppgaver og beskjerder på mine aap.
prøvd på en formulering

2022-09-21 07:19 UTC, sturleh commented on README.md
> +- å bygge lokalt, krever enten koblig mot GCP-dev db eller å [kommentere ut testene i](src/test/kotlin/no/nav/aap/api/søknad/SøknadDBTest.kt)
Lagt dette punktet til

2022-09-27 06:36 UTC, jan-olaveide commented on README.md
> +Den benytter seg av [AAP-FSS-Proxy](https://github.com/navikt/aap-fss-proxy) for interne registertjenester, felles forretningslogikk for disse to repoene er samlet i  [AAP-Domain](https://github.com/
logikk -> verdiobjekter

2022-09-27 06:36 UTC, merged